import { PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import { Header } from "@/components";
import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <Header />
      {children}
    </body>
  </html>
);

export default RootLayout;
